const BoundaryTypeObj = Object.freeze({ "Reservoir": 1, "IA": 3, "WorkStation": 5 })
const PiFieldObj = Object.freeze({ "RainTotalValue": "RainTotalValue", "InflowTotalAverageValue": "InflowTotalAverageValue", "AccumulatedRainfallTotalValue": "AccumulatedRainfallTotalValue" })
const PiTypeObj = Object.freeze({ "Month": "Month", "TenDays": "TenDays" })
const FieldNameObj = Object.freeze({ "InflowTotal": "InflowTotal", "Rain": "Rain", "AccumulatedRainfall": "AccumulatedRainfall" })
const DataTypeObj = Object.freeze({ "Month": "Month", "TenDays": "TenDays" })
